## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using the [`torch.Tensor()`](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [2, 5, 4]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random
numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

[Torch random tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [16]:
# Create a random tensor of size (3, 4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.4631, 0.2882, 0.6513, 0.2396],
        [0.8424, 0.4108, 0.0051, 0.2879],
        [0.9754, 0.8003, 0.6635, 0.2230]])

In [17]:
random_tensors.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [19]:
# Challenge
# Create own size of random tensor
own_random_tensor = torch.rand(3, 4, 4)
own_random_tensor

tensor([[[0.6966, 0.1643, 0.8099, 0.7577],
         [0.0778, 0.5177, 0.7489, 0.8942],
         [0.8402, 0.1656, 0.0059, 0.4559],
         [0.4131, 0.0598, 0.6071, 0.7338]],

        [[0.9408, 0.4627, 0.1640, 0.3417],
         [0.7846, 0.2886, 0.2781, 0.5110],
         [0.9045, 0.4572, 0.8788, 0.0215],
         [0.9549, 0.0449, 0.0049, 0.8607]],

        [[0.1096, 0.6866, 0.3532, 0.8934],
         [0.6318, 0.7469, 0.1928, 0.1778],
         [0.2363, 0.6773, 0.2052, 0.5294],
         [0.1462, 0.0392, 0.6350, 0.2882]]])

### Zeros and Ones

In [20]:
# Create a tensor all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros + random_tensors

tensor([[0.4631, 0.2882, 0.6513, 0.2396],
        [0.8424, 0.4108, 0.0051, 0.2879],
        [0.9754, 0.8003, 0.6635, 0.2230]])

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
random_tensors.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

[Precision in computing](https://en.wikipedia.org/wiki/Single-precision_floating-point_format)

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients wit this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [34]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[8.6757e-01, 6.3234e-01, 2.3919e-04, 2.6235e-01],
        [8.0251e-01, 3.6823e-02, 1.7093e-03, 4.8046e-01],
        [1.2988e-01, 8.9845e-01, 1.7297e-01, 9.6887e-01]])

In [35]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [36]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[8.6757e-01, 6.3234e-01, 2.3919e-04, 2.6235e-01],
        [8.0251e-01, 3.6823e-02, 1.7093e-03, 4.8046e-01],
        [1.2988e-01, 8.9845e-01, 1.7297e-01, 9.6887e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [37]:
# create a tensor with float16 datatype
some_tensor = torch.rand(3, 4, dtype=torch.float16)
print(f"Datatype of tensor: {some_tensor.dtype}")

Datatype of tensor: torch.float16


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [40]:
# Create a tensor and 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [42]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [43]:
# Try out PyTorch built_in function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [47]:
# Element wise multiplication
print(f"{tensor} * {tensor} \nEquals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) 
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [50]:
tensor

tensor([1, 2, 3])

In [49]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [54]:
tensor @ tensor

tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 5.14 ms, sys: 166 µs, total: 5.3 ms
Wall time: 13.5 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.02 ms, sys: 151 µs, total: 1.17 ms
Wall time: 993 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [55]:
# Shapes for matrix multiplications
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_B = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [56]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issuse, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** switches the axes or dimensions of a given tensor.

In [62]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [63]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [67]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape vs above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape vs above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [65]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])