## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using the [`torch.Tensor()`](https://pytorch.org/docs/stable/tensors.html)

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([
    [7, 8],
    [9, 10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[
    [1, 2, 3],
    [4, 5, 6],
    [2, 5, 4]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 4]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 4]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random
numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

[Torch random tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [20]:
# Create a random tensor of size (3, 4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.2611, 0.9326, 0.0577, 0.2202],
        [0.4863, 0.6023, 0.6011, 0.7831],
        [0.1605, 0.3625, 0.1862, 0.4509]])

In [21]:
random_tensors.ndim

2

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [27]:
# Challenge
# Create own size of random tensor
own_random_tensor = torch.rand(3, 4, 4)
own_random_tensor

tensor([[[0.6639, 0.3311, 0.5005, 0.8826],
         [0.8529, 0.8226, 0.5782, 0.4453],
         [0.4025, 0.0143, 0.5498, 0.2994],
         [0.3260, 0.6666, 0.1992, 0.1665]],

        [[0.9479, 0.6545, 0.0365, 0.6321],
         [0.4685, 0.7726, 0.2455, 0.3223],
         [0.5172, 0.5357, 0.8026, 0.1363],
         [0.4388, 0.7342, 0.2771, 0.7645]],

        [[0.2528, 0.7010, 0.1145, 0.7800],
         [0.8324, 0.7895, 0.7277, 0.0613],
         [0.4966, 0.9813, 0.9016, 0.9350],
         [0.0437, 0.3090, 0.3012, 0.2512]]])

### Zeros and Ones

In [29]:
# Create a tensor all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
zeros + random_tensors

tensor([[0.2611, 0.9326, 0.0577, 0.2202],
        [0.4863, 0.6023, 0.6011, 0.7831],
        [0.1605, 0.3625, 0.1862, 0.4509]])

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [32]:
ones.dtype

torch.float32

In [33]:
random_tensors.dtype

torch.float32