# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
b = torch.rand(size=(7, 7))
b

tensor([[0.2630, 0.8753, 0.2049, 0.6945, 0.3885, 0.2733, 0.9611],
        [0.0592, 0.1408, 0.1368, 0.9188, 0.7112, 0.2308, 0.6158],
        [0.6873, 0.9798, 0.4960, 0.7815, 0.0866, 0.5640, 0.5551],
        [0.4481, 0.9363, 0.1892, 0.8383, 0.2947, 0.7596, 0.8034],
        [0.2518, 0.5450, 0.0619, 0.8083, 0.5703, 0.8108, 0.9401],
        [0.7486, 0.1555, 0.7198, 0.9682, 0.3861, 0.9221, 0.7353],
        [0.8814, 0.6490, 0.2039, 0.2489, 0.8298, 0.3195, 0.0555]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
a = torch.randn(size=(1, 7))
# Perform matrix multiplication
c = torch.matmul(b, a.T)
c, c.shape

(tensor([[-1.0369],
         [-0.8316],
         [-0.5233],
         [-0.6874],
         [-0.6918],
         [-0.4650],
         [ 0.7501]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM = 0
torch.manual_seed(RANDOM)

# Create two random tensors
a = torch.rand(size=(7, 7))
b = torch.rand(size=(1, 7))

# Matrix multiply tensors
multi = torch.matmul(a, b.T)
multi, multi.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.randn(size=(2, 3), device=device)
tensor_B = torch.randn(size=(2, 3), device=device)
tensor_A, tensor_B

Device: cuda


(tensor([[-1.6165,  0.5685, -0.5102],
         [-0.9113, -1.1555, -0.2262]], device='cuda:0'),
 tensor([[ 0.6331,  1.6358, -0.3459],
         [ 1.0196, -0.4122,  1.4279]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[ 0.0830, -2.6109],
         [-2.3890, -0.7758]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(f"Maximum: {torch.max(tensor_C)}")
# Find min
print(f"Minimum: {torch.min(tensor_C)}")

Maximum: 0.082986980676651
Minimum: -2.610949754714966


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(f"Maximum Index: {torch.argmax(tensor_C)}")

# Find arg min
print(f"Minimum Index: {torch.argmin(tensor_C)}")

Maximum Index: 0
Minimum Index: 1



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_squeezed = random_tensor.squeeze()

# Print out tensors and their shapes
print(f"Random Tensor:\n{random_tensor}\nRandom Tensor shape:\n{random_tensor.shape}")
print(f"\nSqueezed Tensor:\n{tensor_squeezed}\n\nSqueezed Tensor shape:\n{tensor_squeezed.shape}")

Random Tensor:
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Random Tensor shape:
torch.Size([1, 1, 1, 10])

Squeezed Tensor:
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])

Squeezed Tensor shape:
torch.Size([10])
